Add IOS app to Master Detail Sample
badoo/Decompose pull request #168
Opened 2021-06-16 13:20 UTC by Nikola-Milovic

2021-06-16 17:25 UTC, arkivanov requested changes

2021-06-16 17:25 UTC, arkivanov commented on sample/counter/ios-app/ios-app.xcodeproj/project.pbxproj
> +		933ABDAA2679CDFF00A46B55 /* Counter.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = DC23136C250FF73A00BBC24B /* Counter.framework */; };
Perhaps changes in this file are by accident?

2021-06-16 17:25 UTC, arkivanov commented on sample/master-detail/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
The `.idea` folder should be there?

2021-06-16 17:25 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/DetailsView.swift
> +            ScrollView {
This block is duplicated, maybe extract to an `articleText` function? Looks like [there is an example](https://stackoverflow.com/questions/62895948/how-to-return-a-view-type-from-a-function-in-swift-ui) of how to make a function returning `some View`.

2021-06-16 17:25 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/ListView.swift
> +    var items: [MasterDetail.ArticleListArticle]
Usually in other samples, component views receive the whole component instead of its data. So they could observe changes. And looks like this is actually an issue currently. Can we pass `ArticleList` to the `ListView` and `ArticleDetails` to the `DetailsView`? And then use `ObservableValue`, as in the `Counter` or `TodoApp` examples.

2021-06-16 17:25 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/ListView.swift
> +struct ListView_Previews: PreviewProvider {
When you pass `ArticleList` component to the `ListView`, you can follow this [example](https://github.com/JetBrains/compose-jb/blob/971a2a45ddf4fe456b2cf7bdc141dab7ad67f4c7/examples/todoapp/ios/ios/MainView.swift#L40) for previews.

2021-06-16 17:25 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/RootView.swift
> +func isIOS() -> Bool {
Perhaps you meant "isIphone", because both devices run iOS, right?

2021-06-16 18:19 UTC, Nikola-Milovic commented on sample/counter/ios-app/ios-app.xcodeproj/project.pbxproj
> +		933ABDAA2679CDFF00A46B55 /* Counter.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = DC23136C250FF73A00BBC24B /* Counter.framework */; };
Yeah, this was by mistake.

2021-06-16 18:19 UTC, Nikola-Milovic commented on sample/master-detail/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This also shouldn't be here, I have no idea how it slipped into the commit.

2021-06-16 18:21 UTC, Nikola-Milovic commented on sample/master-detail/app-ios/ios-app/RootView.swift
> +func isIOS() -> Bool {
From what I've read ios should be for iphones and [ipados for ipads](https://en.wikipedia.org/wiki/IPadOS). Would a function name like `deviceRequiresMultiPane()` be more descriptive?

2021-06-16 18:28 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/RootView.swift
> +func isIOS() -> Bool {
Yeah, this should be also fine.

2021-06-18 06:27 UTC, Nikola-Milovic commented on sample/counter/ios-app/ios-app.xcodeproj/project.pbxproj
> +		933ABDAA2679CDFF00A46B55 /* Counter.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = DC23136C250FF73A00BBC24B /* Counter.framework */; };
Should be reverted back to the master version
```
 git checkout origin/master -- sample/counter/ios-app/ios-app.xcodeproj/project.pbxproj
```

2021-06-18 08:52 UTC, arkivanov commented
Thanks for updating the branch @Nikola-Milovic. Do you have a desire to address other concerns? If not, I can merge the PR and to it myself later.

2021-06-18 09:00 UTC, Nikola-Milovic commented
Yeah, I am finishing up the mentioned changes currently. I just firstly went thorough the hassle of fixing the stupid commits I did. I'll push rest of the changes asap. Please do let me know if I resolved the unnessesary commited files successfuly.

2021-06-18 09:05 UTC, arkivanov commented
> Yeah, I am finishing up the mentioned changes currently. I just firstly went thorough the hassle of fixing the stupid commits I did. I'll push rest of the changes asap. Please do let me know if I resolved the unnessesary commited files successfuly.

Thanks for working on this! I marked some comments as resolved, the folder is now clean.

2021-06-18 10:51 UTC, Nikola-Milovic commented on sample/master-detail/app-ios/ios-app/DetailsView.swift
> +            ScrollView {
Something like 

```
@ViewBuilder func getView(text: String, showToolbar : Bool) -> some View {
   if showToolbar {
   // we return the navigation view
   } else {
   // we only return the text view
}
}
```
Kinda confused as to how to extract this into a common function without doing something similar to what I've already done. Or did you mean simply extract the 

```
 ScrollView {
     Text(article.text).padding([.top, .leading, .trailing]).lineLimit(nil)
 }
``` 
into its own function?

2021-06-18 16:24 UTC, arkivanov commented on sample/master-detail/app-ios/ios-app/DetailsView.swift
> +            ScrollView {
Yes, I meant exactly this, just to reduce the code duplication. Just extract the `ScrollView` block.

2021-06-18 18:56 UTC, arkivanov approved these changes

2021-06-18 18:56 UTC, merged