Add documentation for Navigator interface, extension functions, and hierarchy
badoo/Decompose pull request #219
Opened 2021-08-15 09:17 UTC by plusmobileapps

## Description 

- added a new page to the router tab of the documentation for navigation
- added kdoc to the navigator interface 

## Issue 

#179

2021-08-15 16:10 UTC, arkivanov requested changes

2021-08-15 16:10 UTC, arkivanov commented on decompose/src/commonMain/kotlin/com/arkivanov/decompose/NavigatorExt.kt
> + * Drops the configurations at the top of the stack which match the provided [predicate]
The description looks incorrect. The function pops from the top of the stack *while* the predicate returns true.

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +!!! note
Let's just write "The [Router]() interface extends the `Navigator` interface ..."

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +## `Navigator`
Would be better to follow the existing style, let's remove backticks "`"

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +    [`Router`](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/Router.kt) extends [`Navigator`](https://github.com/arkivanov/Decompose/blob/
I think it's enough to provide a link once on the page, and then just write `Navigator`, etc., without the link.

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +val navigator: Navigator<Configuration>
Let's use `Router` in code snippets, as it is most commonly used.

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +![](../media/navigator-popwhile.png)
Having equal configurations in a stack is incorrect. Let's do `ABCD` -> `AB`? `popWhile { it !is B }`

2021-08-15 16:10 UTC, arkivanov commented on docs/router/navigation.md
> +The preceding examples will utilize the following sealed class for showcasing the usage of the `Navigator` extensions with `Configuration.A` as the initial configuration on the stack.
> "with `Configuration.A` as the initial configuration on the stack"

Seems like not exactly the case in some examples?

2021-08-15 16:12 UTC, arkivanov commented on docs/router/navigation.md
> +## `Navigator`
Also perhaps a better title would be "Navigator and Router`, because we describe both

2021-08-16 06:46 UTC, plusmobileapps commented on docs/router/navigation.md
> +The preceding examples will utilize the following sealed class for showcasing the usage of the `Navigator` extensions with `Configuration.A` as the initial configuration on the stack.
That is right, since the diagrams show the initial stack I will just omit that part in the initial explanation 👍

2021-08-16 06:50 UTC, plusmobileapps commented on docs/router/navigation.md
> +![](../media/navigator-popwhile.png)
Didn't realize equal configurations couldn't be in a stack, I can update that 👍

2021-08-16 07:03 UTC, plusmobileapps commented on decompose/src/commonMain/kotlin/com/arkivanov/decompose/NavigatorExt.kt
> + * Pushes the provided [configuration] at the top of the stack
Just an idea which might need to be done after this is merged to use the github image url, but it might be nice to add the `<img>`'s of the navigation samples to the code documentation so that it could be brought up from intellij when a user of decompose is looking at the documentation similar to how [RxJava](https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/core/Single.java#L68) does it. 🤷

2021-08-16 18:59 UTC, arkivanov commented on decompose/src/commonMain/kotlin/com/arkivanov/decompose/NavigatorExt.kt
> + * Pushes the provided [configuration] at the top of the stack
Sounds interesting!

2021-08-17 09:06 UTC, merged